server:
    directory: "/etc/unbound"
    pidfile: "/run/unbound.pid"
    logfile: /var/log/unbound.log
    log-queries: no
    chroot: ""
    num-threads: 1
    num-queries-per-thread: 1024
    do-daemonize: no
    so-reuseport: yes
    ip-transparent: no
    ip-freebind: no
    unwanted-reply-threshold: 0
    rrset-roundrobin: yes
    
    interface: 127.0.0.1
    port: 53

    hide-version: yes
    hide-trustanchor: yes
    hide-identity: yes
    
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    
    tcp-upstream: no
    udp-upstream-without-downstream: no
    tcp-idle-timeout: 15000
    
    qname-minimisation: yes
    qname-minimisation-strict: no
    
    deny-any: yes
    use-caps-for-id: yes
    minimal-responses: yes
    aggressive-nsec: yes
    
    harden-dnssec-stripped: yes
    
    edns-tcp-keepalive: no
    edns-tcp-keepalive-timeout: 0
    
    statistics-interval: 0
    statistics-cumulative: no
    extended-statistics: no
    
    msg-cache-size: 10m
    rrset-cache-size: 50m
    cache-max-ttl: 3600
    cache-min-ttl: 1800
    infra-host-ttl: 1000
    infra-cache-min-rtt: 50
    prefetch: yes