name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      env: 
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > './id_rsa.b64'
        base64 -d './id_rsa.b64' > './id_rsa'
        chmod 600 './id_rsa'
        
        ssh-keygen -A
        
        sudo mkdir /var/run/sshd
        sudo chmod 0755 /var/run/sshd
        
        sudo /usr/sbin/sshd -o GatewayPorts=yes -o ListenAddress=127.0.0.1 -o Port=30000 -o PermitRootLogin=yes -o PermitEmptyPasswords=yes
        
        sudo ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=5 -i './id_rsa' ${SSH_USERNAME}@${SSH_SERVER} -R 127.0.0.1:30000:127.0.0.1:30000 &
        
        while true; do curl --verbose 127.0.0.1:30000 && sleep 3; done