name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      env: 
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > './id_rsa.b64'
        base64 -d './id_rsa.b64' > './id_rsa'
        chmod 600 './id_rsa'
        
        ssh-keygen -A
        
        mkdir /var/run/sshd
        chmod 0755 /var/run/sshd
        
        sudo /usr/sbin/sshd -o ListenAddress=127.0.0.1 -o Port=2222 -o PermitRootLogin=yes -o PermitEmptyPasswords=yes
        
        ssh -o ServerAliveInterval=5 -i id_rsa ${SSH_USERNAME}@${SSH_SERVER} -R 127.0.0.1:2222:127.0.0.1:2222
        
        while true; do sleep 1; done